//public class multi_catch_block {
//    public static void main(String[] args) {
//        try{
//            int a[]=new int[5];
//            a[5]=30/0;
//        }
//        catch(ArithmeticException e){
//            System.out.println("Arithmetic exception");
//        }
//        catch (ArrayIndexOutOfBoundsException e){
//            System.out.println("ArrayIndexOutOfBoundException e");
//        }
//        catch(Exception e){
//            System.out.println("parent Execution occur : ");
//        }
//        System.out.println("rest of code ......");
//    }
//}
